apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../mongodb

namespace: "kustomizationseconddb"

commonLabels:
  monitoringstatus: "critical"


patchesJson6902:
- target:
    version: v1
    kind: Namespace
    name: databasetest
  path: "namespace.patch.json"