apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: "kustomizedemodb"

commonLabels:
  monitoringstatus: "ignore"

resources:
- ./1-namespaces/1-database.yaml
- ./1-namespaces/2-database-limitRange.yaml
- ./1-namespaces/3-database-resourceQuota.yaml
- ./2-storage-class/storage-delete.yaml
- ./3-rbac/dbrole.yaml
- ./4-database/mongo-statefulset.yaml

patchesJson6902:
- target:
    version: v1
    kind: Namespace
    name: databasetest
  path: "namespace.patch.json"