apiVersion: v1
kind: ResourceQuota
metadata:
  name: database-resourcequota
  namespace: databasetest
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "2Gi"
    limits.cpu: "3"
    limits.memory: "4Gi"
