apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  monitoringstatus: "ignore"

commonAnnotations:
  customsecurityservice: "log"

namespace: "kustomizedemodb"

resources:
- output.yaml

patchesJson6902:
- target:
    version: v1
    kind: Namespace
    name: helmmongodb
  path: "namespace.patch.json"