apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: demok8s
spec:
  podSelector:
      matchLabels:
        tier: mysql
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}
