apiVersion: v1
kind: LimitRange
metadata:
  name: mem-cpu-limit-range
  namespace: demok8s
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 1024Mi
    defaultRequest:
      cpu: 50m
      memory: 128Mi
    type: Container